WebApp-prep/CodingWebApp/Pages/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coding.Model;
using CodingWebApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CodingWebApp.Pages
{
    public class DetailsModel : PageModel
    {

        [BindProperty]
        public ListItem SelectedListItem { get; set; }

        private IItemStorage _storage { get; set; }

        public DetailsModel(IItemStorage storage)
        {
            _storage = storage;
        }

        public void OnGet(int id)
        {
            if (id == 0)
            {
                SelectedListItem = new ListItem();
                return;
            }

            SelectedListItem = _storage.GetById(id);
        }

        public IActionResult OnPost()
        {
            _storage.AddItem(SelectedListItem);

            return RedirectToPage("List");
        }

        public IActionResult OnPostCancel()
        {
            return RedirectToPage("List");
        }

        public IActionResult OnPostDelete()
        {
            _storage.RemoveItem(SelectedListItem.Id);
            return RedirectToPage("List");
        }
    }
}

WebApp-prep/CodingWebApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CodingWebApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApp-prep/CodingWebApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodingWebApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebApp-prep/CodingWebApp/Pages/List.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Coding.Model;
using CodingWebApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CodingWebApp.Pages
{
    public class ListModel : PageModel
    {
        public List<ListItem> Items = new List<ListItem>();

        private IItemStorage _storage { get; set; }

        public ListModel(IItemStorage storage)
        {
            _storage = storage;
        }

        public void OnGet()
        {
            Items = _storage.GetAllItems();
        }
    }
}

WebApp-prep/CodingWebApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CodingWebApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApp-prep/CodingWebApp/Pages/Details.cshtml
@page "{id}"
@model CodingWebApp.Pages.DetailsModel
@{
}


<div>
    <form id="frmMain" method="post">
        <input id="txtSelectedId" type="hidden" value="@Model.SelectedListItem.Id">
        <table>
            <tr>
                <td><label for="txtName">Name</label></td>
                <td><input id="txtName" name="name" value="@Model.SelectedListItem.Name"></td>
            </tr>
            <tr>
                <td><label for="txtDescription">Description</label></td>
                <td><input id="txtDescription" name="description" value="@Model.SelectedListItem.Description"></td>
            </tr>
            <tr>
                <td colspan="2">
                    <div style="display: flex">
                        <button class="btn btn-warning" asp-page-handler="cancel">Cancel</button>
                        @if (Model.SelectedListItem.Id > 0)
                        {
                        <button class="btn btn-danger" asp-page-handler="delete">Delete</button>
                        }
                        <button class="btn btn-success" type="submit">Save</button>
                    </div>
                </td>
            </tr>
        </table>
    </form>
</div>

WebApp-prep/CodingWebApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApp-prep/CodingWebApp/Pages/List.cshtml
@page
@model CodingWebApp.Pages.ListModel
@{
}

<a href="/Details/0">Add New</a>
<ul id="lstList">
    @foreach (var item in Model.Items)
    {
        <li>@item.Name</li>
    }
</ul>

<table>
    <thead>
        <tr>
            <th>
                Id
            </th>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Items)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td><a href="Details/@item.Id">Edit</a></td>
            </tr>
        }
    </tbody>
</table>

WebApp-prep/CodingWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CodingWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">CodingWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/List">List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CodingWebApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>